/**
 * This utility function converts timestamp string into datetime string
 * @param {string} timestamp - The varible contain datetime string generated by Date.now
 * @returns {string} - It returns a string containing date.
 */
// to get the current date derived from the Date.now()
export function getCurrentDate(timestamp) {
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

    // deriving the date from timestamp
    const date = new Date(timestamp);
    const day = days[date.getDay()];
    const dayOfMonth = date.getDate();
    const month = months[date.getMonth()];
    const hours = date.getHours();
    const minutes = date.getMinutes();
    const ampm = hours >= 12 ? 'PM' : 'AM';

    // Format single-digit hours and minutes with leading zeros
    const formattedHours = (hours % 12 || 12).toString().padStart(2, '0'); // Convert 0 to 12 for AM/PM display
    const formattedMinutes = minutes.toString().padStart(2, '0');

    return `${day}, ${dayOfMonth} ${month} ${formattedHours}:${formattedMinutes} ${ampm}`;

}
